# Generated by Django 5.0.1 on 2024-01-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
