# Generated by Django 5.0.1 on 2024-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance_App', '0004_rename_userpolices_userpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('select_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='userpolicy',
        ),
    ]
