# Generated by Django 5.0.1 on 2024-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance_App', '0007_user_policies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userpolicies',
        ),
        migrations.AlterField(
            model_name='user_policies',
            name='grant_policy',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
