# Generated by Django 5.0.1 on 2024-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance_App', '0009_user_policies_new_delete_user_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
    ]
